version: '2'
services:
  proxy:
    network_mode: bridge
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/reckerops-nginx.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhosts:/etc/nginx/vhost.d
  ssl:
    network_mode: bridge
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhosts:/etc/nginx/vhost.d

volumes:
    certs: {}
    html: {}
    vhosts: {}
