---
driver:
  name: ec2
  region: us-west-2
  subnet_id: subnet-fb283ea3
  security_group_ids: [sg-49b2a831]
  aws_ssh_key_id: reckerops-build

transport:
  ssh_key: ~/.ssh/reckerops-build.pem

provisioner:
  name: salt_solo
  formula: salt
  state_top_from_file: true
  pillars:
    top.sls:
      base:
        '*':
          - everything
    everything.sls:
      hosts:
        example.com:
          upstream: http://127.0.0.1:8000

platforms:
  - name: debian
  - name: ubuntu-14.04
  - name: centos-7

suites:
  - name: default
