---
driver:
  name: ec2
  region: us-west-2
  subnet_id: subnet-fb283ea3
  security_group_ids: [sg-49b2a831]
  aws_ssh_key_id: reckerops-build

transport:
  ssh_key: ~/.ssh/reckerops-build.pem

provisioner:
  name: salt
  local_state_tree: images/salt
  local_pillar_roots: images/pillar
  state_output: mixed

platforms:
  - name: debian

suites:
- name: default
  provisioner:
    minion_config: images/configs/strongbadia.yml
