---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: bootstrap
  is_file_root: true
  state_top:
    base:
      '*':
        - bootstrap

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
