version: '2'

services:

  cfn:
    container_name: cfn
    image: arecker/reckerops/cfn:latest
    build: ./cfn
    network_mode: bridge
    env_file:
      - ./secrets/aws.env

  dns:
    container_name: dns
    image: arecker/reckerops/dns:latest
    build: ./dns
    network_mode: bridge
    env_file:
      - ./secrets/aws.env
      - ./secrets/cloudflare.env

  ami:
    container_name: ami
    image: arecker/reckerops/ami:latest
    build: ./ami
    network_mode: bridge
    env_file:
      - ./secrets/aws.env
    volumes:
      - ./secrets/kitchen.pem:/kitchen.pem:ro
