version: '2'

services:

  dns:
    image: arecker/reckerops/dns:latest
    build: ./dns
    network_mode: bridge
    env_file:
      - ./secrets/secrets.env

  cloudformation:
    image: arecker/reckerops/cloudformation:latest
    build: ./cloudformation
    network_mode: bridge
    env_file:
      - ./secrets/secrets.env

  images:
    image: arecker/reckerops/images:latest
    build: ./images
    network_mode: bridge
    environment:
      - CLOUDFLARE_EMAIL='alex@reckerfamily.com'
    env_file:
      - ./secrets/secrets.env
    volumes:
      - ./secrets/build.pem:/build.pem
