version: '2'

services:

  lambda:
    container_name: lambda
    image: arecker/reckerops/lambda:latest
    build: ./lambda
    network_mode: bridge
    env_file:
      - ./secrets/aws.env

  cfn:
    container_name: cfn
    image: arecker/reckerops/cfn:latest
    build: ./cfn
    network_mode: bridge
    env_file:
      - ./secrets/aws.env

  dns:
    container_name: dns
    image: arecker/reckerops/dns:latest
    build: ./dns
    network_mode: bridge
    env_file:
      - ./secrets/aws.env
      - ./secrets/cloudflare.env

  kitchen:
    container_name: kitchen
    image: arecker/reckerops/kitchen:latest
    build:
      context: ./ami
      dockerfile: Dockerfile.kitchen
    network_mode: bridge
    env_file:
      - ./secrets/aws.env
    volumes:
      - ./secrets/kitchen.pem:/kitchen.pem:ro
