version: '2'

services:

  dns:
    container_name: dns
    image: arecker/reckerops/dns:latest
    build: ./dns
    network_mode: bridge
    env_file:
      - ./secrets/secrets.env

  cloudformation:
    container_name: cloudformation
    image: arecker/reckerops/cloudformation:latest
    build: ./cloudformation
    network_mode: bridge
    env_file:
      - ./secrets/secrets.env

  images:
    container_name: images
    image: arecker/reckerops/images:latest
    build: ./images
    network_mode: bridge
    env_file:
      - ./secrets/secrets.env
    volumes:
      - ./secrets/build.pem:/build.pem
