version: '2'

services:

  db:
    image: mysql
    restart: always
    network_mode: bridge
    volumes: [ 'db:/var/lib/mysql' ]
    env_file: [ 'secrets.env' ]

  wp:
    depends_on: [ db ]
    image: wordpress:latest
    restart: always
    network_mode: bridge
    links: [ 'db:mysql' ]
    volumes: [ 'www:/var/www/html' ]
    env_file: [ 'secrets.env' ]

volumes:
  db: {}
  www: {}
