version: '2'
services:
  nginx:
    network_mode: bridge
    image: jwilder/nginx-proxy
    container_name: proxy-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
  ssl:
    network_mode: bridge
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: proxy-ssl
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=proxy-nginx

volumes:
  certs: {}
  vhosts: {}
  html: {}
