---
driver:
  name: ec2
  region: us-west-2
  subnet_filter:
    tag: 'Name'
    value: 'build'
  security_group_filter:
    tag: 'Name'
    value: 'build'
  aws_ssh_key_id: reckerops-kitchen

transport:
  ssh_key: /kitchen.pem

provisioner:
  name: salt
  local_state_tree: salt
  local_pillar_roots: pillar
  minion_config: minion/kitchen

platforms:
  - name: debian

suites:
- name: default
