Description: Personal Password Vault


Parameters:

  RepositoryName:
    Type: String
    Description: Name of the Git Repository
    Default: vault


Resources:

  Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName:
        Ref: RepositoryName

  User:
    Type: AWS::IAM::User
    Properties:
      UserName:
        Fn::Join: [ "-", [ { "Ref": "AWS::StackName" }, { "Ref": "AWS::Region" } ] ]
      Policies:
        - PolicyName: VaultCodeCommitPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  Fn::GetAtt: [ Repository, Arn ]
                Action:
                  - 'codecommit:BatchGetRepositories'
                  - 'codecommit:Get*'
                  - 'codecommit:List*'
                  - 'codecommit:Put*'
                  - 'codecommit:Test*'
                  - 'codecommit:Update*'
                  - 'codecommit:GitPull'
                  - 'codecommit:GitPush'


Outputs:

  CloneUrl:
    Description: Clone URL
    Value:
      Fn::GetAtt: [ Repository, CloneUrlSsh ]
