- hosts: proxies
  roles:
    - role: firewall
      public: True

- hosts: masters
  roles:
    - role: firewall
      public: false
    - docker
    - role: nfs
      consumers:
        - 192.155.82.135
        - 45.33.61.211
        - 173.230.148.165

- hosts: workers
  roles:
    - role: firewall
      public: false
    - docker
