---
driver:
  name: vagrant

platforms:
  - name: debian-9

provisioner:
  name: salt_solo

suites:
  - name: locale
    provisioner:
      formula: locale
      state_top:
        base:
          '*':
            - locale
  - name: docker
    provisioner:
      formula: docker
      state_top:
        base:
          '*':
            - docker
  - name: letsencrypt
    provisioner:
      formula: letsencrypt
      state_top:
        base:
          '*':
            - letsencrypt
